channels:
  - conda-forge
dependencies:
  - python=3.8.13
  - numpy=1.21.6
  - pandas=1.4.2
  - sphinx=6.1.3
  - sphinxcontrib-napoleon=0.7
  - sphinx-rtd-theme=1.2.0
  - nbsphinx=0.9.1
  - PyYAML=6.0
  - fsspec=2022.8.2
